### 사이킷런 내장 예제 데이터

**용어정리**
1. 피처
- 데이터에서 타겟값을 제외한 나머지 속성을 모두 피처로 지칭한다
2. 레이블, 클래스, 타겟(값), 결정(값)
- 지도학습(supervised learning) 시 데이터의 학습을 위해 주어지는 데이터의 정답 데이터를 의미한다. 지도학습 중 분류의 경우 이 결정값을 레이블이나 클래스로 지칭한다 (회귀를 포함해서 주로 타겟값이라고 많이 부르는 것 같다)

**분류란?**
- 분류는 피처들의 패턴을 읽어서 답(타겟값 혹은 레이블)을 예측하기 위한 모델을 만들기 위한 학습 방법. 대표적인 지도학습 방법 중 하나다.
- 지도학습: 명확한 정답이 주어지는 데이터를 먼저 학습한 뒤 미지의 정답 데이터를 예측하는 방식. 이때 학습을 위한 데이터세트를 **학습 데이터 세트**, 모델의 예측 성능을 평가하기 위한 데이터세트를 **테스트 데이터 세트**라고 부른다.


In [2]:
from sklearn.datasets import load_iris

In [19]:
iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [21]:
keys = iris_data.keys()
print("Iris 데이터 세트의 키:", keys)

Iris 데이터 세트의 키: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


데이터 세트의 키는 보통 data, target, feature_names, target_names, DESCR을 포함한다
- data: 피처의 데이터 세트를 의미한다. 여기서는 4개의 피처에 대한 값들만 2차원의 ndarray로 구성되어 있다
- target: 분류에서는 레이블 값, 회귀일 경우에는 숫자 결과값 데이터 세트
- feature_names: 피처가 ndarray로 되어 있기 때문에 컬럼이 없다. 그에 맞게 메타데이터로 피처의 이름을 저장하는 곳
- target_names: 타겟 값도 ndarray로 되어 있기 때문에 컬럼이 없다. 그에 맞게 개별 레이블의 이름을 저장하는 곳
- DESCR: 데이터 세트 및 각 피처에 대한 설명이 저장된 곳

In [20]:
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
print("feature_names의 type:", type(iris_data.feature_names))
print("feature_names의 shape: ", len(iris_data.feature_names)) # feature_names는 target_names와 달리 list라서 shape가 없음
print(iris_data.feature_names)

feature_names의 type: <class 'list'>
feature_names의 shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [16]:
print("target_names의 type:", type(iris_data.target_names))
print("target_names의 shape:", iris_data.target_names.shape)
print(iris_data.target_names)

target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: (3,)
['setosa' 'versicolor' 'virginica']


In [21]:
print("data의 type:", type(iris_data.data))
print("data의 shape:", iris_data.data.shape)
print(iris_data.data)

data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1

In [22]:
print("target의 type:", type(iris_data.target))
print("target의 shape:", iris_data.target.shape)
print(iris_data.target)

target의 type: <class 'numpy.ndarray'>
target의 shape: (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### 사이킷런을 이용하여 붓꽃(Iris) 데이터 품종 예측하기

In [31]:
# 사이킷런 버전 체크
import sklearn
print(sklearn.__version__)

1.3.0


**1. 필요 모듈 및 데이터 세트 로딩**

In [34]:
# iris 품종 예측을 위한 사이킷런 모듈 import
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [59]:
# iris 데이터 로딩
iris = load_iris()

# 피처데이터와 타겟데이터를 합쳐서 iris_df 데이터프레임 생성
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

**2. 학습 데이터셋과 테스트 데이터셋으로 분리**

In [60]:
iris_data = iris.data
iris_target = iris.target

In [70]:
iris_data.shape

(150, 4)

In [64]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_target, test_size=0.2, random_state=11)

In [76]:
# test_size를 0.2로 해서 기존 150개의 피처 및 타겟 데이터셋이 120, 30개로 쪼개짐
print("iris_data (피처 데이터셋)의 shape:", iris_data.shape)
print("iris_target (타겟 데이터셋)의 shape:", iris_target.shape)
print("X_train의 (학습용 피처 데이터셋)의 shape:", X_train.shape)
print("y_train의 (학습용 타겟 데이터셋)의 shape:", y_train.shape)
print("X_test의 (테스트용 피처 데이터셋)의 shape:", X_test.shape)
print("y_test의 (테스트용 타겟 데이터셋)의 shape:", y_test.shape)

iris_data (피처 데이터셋)의 shape: (150, 4)
iris_target (타겟 데이터셋)의 shape: (150,)
X_train의 (학습용 피처 데이터셋)의 shape: (120, 4)
y_train의 (학습용 타겟 데이터셋)의 shape: (120,)
X_test의 (테스트용 피처 데이터셋)의 shape: (30, 4)
y_test의 (테스트용 타겟 데이터셋)의 shape: (30,)


**3. 학습 데이터셋으로 학습(train) 수행**

In [77]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

**4. 테스트 데이터셋으로 예측(predict) 수행**

In [78]:
# 학습이 된 dt_clf로 테스트 데이터 예측 수행하고 그 예측 수행값을 pred에 저장
pred = dt_clf.predict(X_test)

In [79]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

**5. 모델의 예측 정확도 평가**

In [81]:
from sklearn.metrics import accuracy_score
print(f"예측 정확도: {accuracy_score(y_test, pred):.3f}")

예측 정확도: 0.933
